version: "3"
services:
  web_itbookstore:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3016:3000"
    volumes: 
      - ./itbookstore:/opt/app
      - gem_cache_itbookstore:/gems
    env_file: 
      - .env/development/database_itbookstore
      - .env/development/web_itbookstore
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_itbookstore
    networks:
      - network
  webpack_dev_server_itbookstore:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "4017:4017"
    volumes: 
      - ./itbookstore:/opt/app
      - gem_cache_itbookstore:/gems
    env_file: 
      - .env/development/database_itbookstore
      - .env/development/web_itbookstore
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_itbookstore:
    image: postgres
    env_file: 
      - .env/development/database_itbookstore
    volumes: 
      - db_data_itbookstore:/var/lib/postgresql/data
    networks:
      - network
  redis_itbookstore:
    image: redis
    networks:
      - network

volumes: 
  db_data_itbookstore:
  gem_cache_itbookstore:
networks:
  network: